version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
  pre_build:
    commands:
      - echo Pre-build stage...
  build:
    commands:
      - echo Build started on `date`
      - python main.py
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - hello

